### ISSUE TITLE
Create new docker image with latest dependencies

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/solid-crud-tests#55]
I'm trying to push a Docker image for v5.3.0. It seems the service where hub.docker.com does the build for you has been removed from our free account, so you now have to build locally and then do a Docker push.

**Comment by mrvahedi68** [comment]
Ok! I will build locally and push the final image to docker hub.

**Comment by michielbdejong** [comment]
```sh
docker build -t solidtestsuite/solid-crud-tests:v5.3.0 .
docker push solidtestsuite/solid-crud-tests:v5.3.0
```

**Comment by michielbdejong** [comment]
```
v5.3.0: digest: sha256:db263ab9f376f6c644059115b13730c8805952f64499103db46615e402eedf01 size: 3056
```
https://hub.docker.com/repository/docker/solidtestsuite/solid-crud-tests
https://hub.docker.com/layers/210513199/solidtestsuite/solid-crud-tests/v5.3.0/images/sha256-db263ab9f376f6c644059115b13730c8805952f64499103db46615e402eedf01?context=repo
